FROM bentoml/quickstart:latest

USER root

WORKDIR /home/bentoml/

RUN pip install torch

RUN pip install numpy

RUN pip install pandas

RUN pip install scikit-learn
RUN pip install seaborn
RUN pip install matplotlib
